version: 2
jobs:
 build:
   machine: true

   steps:
     - checkout
     - run:
          name: Install Node LTS
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            nvm alias default node
            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
     - run:
          name: Install latest Yarn
          command: |
            set +e
            sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install yarn
     - run:
          name: Server - Install, Build and Lint
          command: yarn && yarn build
     - run:
          name: Deploy Docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn publish-docker
            fi